name: commit_info
description: Safely get version control information in a Dart project.
version: 0.3.0
license: MIT
homepage: https://github.com/lalomartins/dart-commit-info

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  build: ^4.0.2
  path: ^1.9.1

dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.10.3
  lints: ^5.1.1

executables:
  initialize:
